### ISSUE TITLE
Keyboard initially active

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-android#14]
When Replete launches on iOS, the keyboard is active with the cursor in the form entry field.

I don't have access to a real Android device. The image below is made using the emulator. If this could be done on Android, then the user can just start typing when the app launches (and there would be no need for the "Type in here" placeholder).

<img width="692" alt="napkin 4 01-20-19 9 44 10 am" src="https://user-images.githubusercontent.com/1723464/51440710-f0606780-1c97-11e9-8fff-5cecbf90c3a8.png">

**Comment by roman01la** [comment]
Same behavior on real device. I'll take a look.

**Comment by roman01la** [comment]
Resolved in ce560d1
