### ISSUE TITLE
Keyboard autosuggest off

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-android#15]
On iOS, I have the keyboard autosuggestion off (suggesting words in English doesn't seem to be very useful, and this takes up more space).

<img width="602" alt="napkin 4 01-20-19 9 55 02 am" src="https://user-images.githubusercontent.com/1723464/51440866-74ffb580-1c99-11e9-8a75-4747d2dccf3b.png">

**Comment by roman01la** [comment]
From what I've learnt most Android devices use custom Google's keyboard (GBoard) by default which doesn't care about autosuggestions setting, so we don't really have control over it unfortunately.
