### ISSUE TITLE
Darker text for entered forms

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-android#17]
When a form is entered, it is shown in the UI as light gray. I had found that this was difficult to read and darkened it with https://github.com/replete-repl/replete-ios/commit/34eb903de5ad8f7f82ecb7a0d8e10d014fdde9d7

Perhaps the Android port is using gray, or the font is thinner, but the visual effect reminds me of the way the iOS version used to look.

Compare the contrast with the `(+ 1 2)` forms below:

<img width="918" alt="image" src="https://user-images.githubusercontent.com/1723464/51440914-e5a6d200-1c99-11e9-84ee-dd5b471587c4.png">

**Comment by roman01la** [comment]
Makes sense!

**Comment by roman01la** [comment]
Resolved in 160f096

**Comment by roman01la** [comment]
@mfikes Can we close this one? What do you think?
