### ISSUE TITLE
Rotating the screen clears the REPL content

### ISSUE THREAD

**Issue by icamts** [replete-repl/replete-android#23]
After screen rotation i can see only the REPL initial content

ClojureScript 1.10.439
Docs: (doc function-name)
(find-doc "part-of-name")
Source: (source function-name)
Results: Stored in *1, *2, *3,
an exception in *e

Anything previously entered disappeared.

**Comment by roman01la** [comment]
Can confirm this on my device as well. Thanks for bug report!

**Comment by roman01la** [comment]
Resolved in d45a41f60
