### ISSUE TITLE
History of commands

### ISSUE THREAD

**Issue by DjebbZ** [replete-repl/replete-android#25]
The app would be much more usable if we could easily access the history of commands. It's so easy to mistype something on mobile that if I could just get a previous command and fix my typo before re-running it.

Maybe it exists already but I haven't found how to access it.

**Comment by roman01la** [comment]
On both iOS and Android you can copy an item by tapping on it and choosing copy action

**Comment by DjebbZ** [comment]
Got it, thanks!
