### ISSUE TITLE
Terminate execution on timeout

### ISSUE THREAD

**Issue by roman01la** [replete-repl/replete-android#27]
The app should terminate execution in V8 after a certain timeout (30s?) to prevent blocking when user executes something like `(range)`

**Comment by mfikes** [comment]
One tricky aspect of this is that you really don't know if the user is trying to solve a lengthy problem.

**Comment by roman01la** [comment]
Good point!

**Comment by mfikes** [comment]
On iOS, if I happen to do this accidentally, I force the app to quit using the operating system's mechanism. (This is analogous to the case where you quit a conventional Clojure REPL when accidentally evaluating a long-running calculation.)

**Comment by roman01la** [comment]
Hm, so now Android kills the app as well if it blocks for too long. Maybe that's a good enough mechanism then? :)

**Comment by roman01la** [comment]
In the docs it says that the app exists after 5s. Seems to be ok for us.
