### ISSUE TITLE
http get not working

### ISSUE THREAD

**Issue by monkeygroover** [replete-repl/replete-android#38]
Pixel 2, Replete version 2.0

Hi, I tried the following:

```
(require 'replete.http)
(replete.http/get "https://replete-repl.org")
```

but I get `{:error, nil}`

same with `(replete.http/get "https://www.google.co.uk")`  etc.

I note that http doesn't work, but there is already an issue covering that.

Am I doing something wrong, or is this a bug?

Thanks

**Comment by roman01la** [comment]
Hi. It's already fixed and will be released soon

**Comment by mfikes** [comment]
You can also try the open beta, which is currently available in the Google Play store.

**Comment by monkeygroover** [comment]
Thanks, yeah the beta is working fine. cheers, will close.
