### ISSUE TITLE
64-bit support

### ISSUE THREAD

**Issue by mfikes** [replete-repl/replete-android#39]
When releasing Replete Android 2.0.1, a warning popped up regarding the need for 64-bit support coming up in the future. Dunno if this was just a generic warning or was triggered by something in Replete Android. It provided this link:

https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by roman01la** [comment]
Looks like this was addressed in J2V8 https://github.com/eclipsesource/J2V8/issues/384#issuecomment-487207216 I'll have to take a look and update deps

**Comment by mfikes** [comment]
Build 15 is showing this positive indicator in the Google Play developer console:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1723464/64490749-45a0b780-d22e-11e9-8eac-bd0a022750be.png">
