### ISSUE TITLE
Handle defmacro

### ISSUE THREAD

**Issue by roman01la** [replete-repl/replete-android#5]
Port handling of `defmacro` via [chivorcam](https://github.com/mfikes/chivorcam), [see](https://github.com/replete-repl/replete-ios/blob/master/Replete/AppDelegate.m#L740-L743) for reference.

**Comment by roman01la** [comment]
Added in 2d9f97a2

**Comment by roman01la** [comment]
@mfikes When `requiring.core` it pulls in `core$macros.clj.cache.json, but only `core$macros.cljc.cache.json` is present in `replete-shared` build output. Is this a known issue?

**Comment by roman01la** [comment]
@mfikes Looks like any macros ns that is required is being read from `clj` instead of `cljc`. Verified with spec and core.async

This might be related to https://github.com/replete-repl/replete-ios/issues/111

**Comment by mfikes** [comment]
Oh, interesting. I hadn't noticed that.

**Comment by roman01la** [comment]
Hm, for some reason I can't reproduce it anymore...

**Comment by roman01la** [comment]
Ok, I'm definitely getting `clj` instead of `cljc`, but can't figure out when exactly this happens

**Comment by roman01la** [comment]
macros loading resolved in 2826719735ef
