### ISSUE TITLE
Duplicates characters while typing

### ISSUE THREAD

**Issue by PrestanceDesign** [replete-repl/replete-android#54]
Hi,

As you can see this screencast, I have a strange behavior while typing:
https://drive.google.com/file/d/102AhzeJZwcjaoOseG8Cyz3-A-u7RmsLw/view?usp=sharing

Best regards.

**Comment by PrestanceDesign** [comment]
I close this issue because obviously this isn't a direct Replete bug...this is causing with the default Keyboard on Xiamomi phone (Facemoji).
I switch on Gboard and I can again using Replete.
 
Anyway, I encountered this keyboard issue only with Replete app.

**Comment by ComedyTomedy** [comment]
I'd like to reopen this issue! I'm experiencing it with Gboard, and it makes replete almost unusable.

Comments on Google Play suggest that predictive text is to blame (I'd test, but can't figure out how to disable it).

I think there's a way to mark a text field as non-completable (as for example a password field would be).

**Comment by ComedyTomedy** [comment]
Ah just read on another issue that Gboard doesn't respect the autocorrect setting. But I've definitely experienced non-completing text fields.

Either way this is still an issue.

Checking if I can tag you to consider re-opening @roman01la @mfikes

**Comment by roman01la** [comment]
There might be issues on slower devices because we are sending input text to JS VM to process it with Parinfer and set back. I remember trying to solve this but had no luck unfortunately. Perhaps someone can take a look at this part? Or maybe find Java/Kotlin port of Parinfer, I've seen one but it wasn't very usable.

**Comment by ComedyTomedy** [comment]
Yes, appears to be related to device speed. Closing FB messenger and another VM fixed it for me :) Thanks for the pointer!
